# application.yml
server:
  port: 8080
  servlet:
    context-path: /api

media:
  root-path: /home/spartan/media
  supported-video-types:
    - .mp4
    - .webm
    - .mkv
  supported-audio-types:
    - .mp3
    - .wav
    - .flac
  supported-subtitle-types:
    - .srt
    - .vtt
  max-depth: 3
  max-file-size: 2147483648 # 2GB

spring:
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
  web:
    resources:
      add-mappings: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: debug