# application.yml
spring:
  application:
    name: media-files
  profiles:
    active: docker

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always